import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/redux/provider";
import LeftSidebar from "@/components/LeftSideBar";
import RightSidebar from "@/components/RightSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {" "}
          {/* Wrap everything in Redux Provider */}
          <div className="flex flex-col h-screen">
            <Navbar />

            <div className="flex flex-1">
              <LeftSidebar />
              <main className="flex-1 p-4">{children}</main>
              <RightSidebar />
            </div>

            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
